import re
from pathlib import Path
import pandas as pd

NAME_RE = re.compile(r"-t(\d+\.\d+)(?:-(.+))?$")
OUT = Path("docs/results.md")


def _bool(s: pd.Series) -> pd.Series:
    return s.astype(str).str.lower().isin(["true", "1", "1.0"])


def summarize(csv: Path) -> dict | None:
    df = pd.read_csv(csv, dtype=str)
    if df.empty or "passed" not in df.columns:
        return None
    m = NAME_RE.search(csv.stem)
    tags = "n/a (pre-tagging)"
    if "tags" in df.columns:
        t = df["tags"].fillna("").str.split(";").explode()
        t = t[t != ""]
        tags = ", ".join(f"{k} x{v}" for k, v in t.value_counts().head(3).items()) or "none"
    return {
        "model": df["model"].iloc[0], "engine": df["engine"].iloc[0],
        "temp": df["temperature"].iloc[0],
        "tasks": m.group(2) if m and m.group(2) else "core",
        "runs": len(df), "pass": _bool(df["passed"]).mean(),
        "clean": _bool(df["clean"]).mean() if "clean" in df.columns else float("nan"),
        "latency": pd.to_numeric(df["latency_s"], errors="coerce").mean(),
        "tokens": pd.to_numeric(df["tokens"], errors="coerce").mean(),
        "tags": tags,
    }


def build_report(results_dir: Path = Path("evals/results")) -> str:
    rows = [r for r in (summarize(c) for c in sorted(Path(results_dir).glob("*.csv"))) if r]
    rows.sort(key=lambda r: (r["tasks"], r["model"], r["engine"], r["temp"]))
    lines = [
        "# Eval results",
        "",
        "Generated by `make report` from `evals/results/*.csv`. Do not edit by hand.",
        "Pass rate is the share of runs where every check passed. Clean is the share of runs",
        "with no failed tool actions. Sample sizes are small, so treat differences of a few",
        "points as noise; repeated runs at temperature 0.7 vary from sample to sample.",
        "",
        "| Task set | Model | Engine | Temp | Runs | Pass rate | Clean | Latency s | Tokens | Top failure tags |",
        "|---|---|---|---|---|---|---|---|---|---|",
    ]
    for r in rows:
        lines.append(
            f"| {r['tasks']} | {r['model']} | {r['engine']} | {r['temp']} | {r['runs']} "
            f"| {r['pass']:.2f} | {r['clean']:.2f} | {r['latency']:.1f} | {r['tokens']:.0f} "
            f"| {r['tags']} |")
    return "\n".join(lines) + "\n"


def main():
    OUT.parent.mkdir(parents=True, exist_ok=True)
    text = build_report()
    OUT.write_text(text)
    print(f"wrote {OUT} ({text.count(chr(10)) - 9} rows)")


if __name__ == "__main__":
    main()
